apiVersion: v1
kind: Pod
metadata:
  name: my-pod-1
  labels:
    name: my-pod-1
    type: backend
    projectname: javaApp
spec:
  containers:
  - name: my-pod-1
    image: emreeoozell/devops-application-001:v001
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 9095
---
apiVersion: v1
kind: Pod
metadata:
  name: my-pod-2
  labels:
    name: my-pod-2
    type: backend
    projectname: javaApp
spec:
  containers:
  - name: my-pod-2
    image: emreeoozell/devops-application-001:v001
    resources:
      limits:
        memory: "256Mi"
        cpu: "500m"
    ports:
      - containerPort: 9096

