apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-application-001
  labels:
    name: my-pod-1
    type: backend
    projectname: javaApp


spec:
  replicas: 5
  selector:
    matchLabels:
      app: devops-application-001
  template:
    metadata:
      labels:
        app: devops-application-001


    spec:
      containers:
      - name: devops-application-001
        image: emreeoozell/devops-application-001:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 9090
